name: Bearer PR Check

on:
  push:
    paths:
      - 'microservice/**'
    branches:
      - main
  pull_request:
    paths:
      - 'microservice/**'
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  rule_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./microservice/app
    steps:
      - uses: actions/checkout@v4
      - name: Bearer
        uses: bearer/bearer-action@v2